// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var $html, $video, init, toggleHD, toggleModelInfo, videoIsHD;

    $video = $('#video');
    $html = $('html');
    toggleModelInfo = function() {
      return $html.toggleClass('modelinfo-hidden');
    };
    videoIsHD = function() {
      return $video.attr('src') === '/poster_wide.jpg';
    };
    toggleHD = function() {
      return $html.toggleClass('hd-video', videoIsHD());
    };
    init = function() {
      return toggleHD();
    };
    $video.hammer().on('tap', toggleModelInfo);
    return init();
  });

}).call(this);
