// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var $html, $video, init, toggleHD, toggleModelInfo, videoIsHD;

    toggleModelInfo = function() {
      return $html.toggleClass('modelinfo-hidden');
    };
    videoIsHD = function() {
      return ($video.src === '/poster_wide.jpg') != null;
    };
    toggleHD = function() {
      return $html.toggleClass('hd-video');
    };
    init = function() {
      if (videoIsHD()) {
        return toggleHD();
      }
    };
    $video = $('#video');
    $html = $('html');
    $video.hammer().on('tap', toggleModelInfo);
    return init();
  });

}).call(this);
