// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var $html, $sidebar, $toggle, $video, toggleFullScreen, toggleInfoBar;

    $toggle = $('#toggle');
    $sidebar = $('#sidebar');
    $video = $('#video');
    $html = $('html');
    toggleFullScreen = function() {
      return $html.toggleClass('fullscreen');
    };
    toggleInfoBar = function() {
      return $html.toggleClass('info-hidden');
    };
    Hammer($toggle[0]).on('tap', toggleFullScreen);
    Hammer($sidebar[0]).on('swiperight', toggleFullScreen);
    Hammer($video[0]).on('tap', toggleInfoBar);
  });

}).call(this);
